### ISSUE TITLE
Error using python 3.8

### ISSUE THREAD

**Issue by radostyle** [natasha/ipymarkup#2]
Traceback (most recent call last):
  File ".../...py", line 1, in <module>
    from ipymarkup import show_box_markup
  File ".../.venv/lib/python3.8/site-packages/ipymarkup/__init__.py", line 2, in <module>
    from .markup import *  # noqa
  File ".../.venv/lib/python3.8/site-packages/ipymarkup/markup.py", line 6, in <module>
    from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (.../.pyenv/versions/3.8.1/lib/python3.8/cgi.py)

**Comment by radostyle** [comment]
Should import escape from html rather than cgi
`from html import escape
`

**Comment by radostyle** [comment]
I guess you've already found it.
https://github.com/natasha/ipymarkup/commit/b4ae7c5f3131e3b8293417d10df23595e62d2211

**Comment by kuk** [comment]
Fixed in https://github.com/natasha/ipymarkup/commit/b4ae7c5f3131e3b8293417d10df23595e62d2211

Try `pip install ipymarkup==0.6.0 `
